export const ADD_USER = "ADD_USER";
export const FETCH_USERS = "FETCH_USERS";
export const USERS_FETCHED = "USERS_FETCHED";
export const USERS_FETCHED_SENT_TO_CONVERSION = "USERS_FETCHED_SENT_TO_CONVERSION";
export const DATA_CONVERTED_TO_OBJ_AND_SENT_TO_REDUCER = "DATA_CONVERTED_TO_OBJ_AND_SENT_TO_REDUCER";
export const DATA_CONVERTED_BACK_TO_ARRAY = "DATA_CONVERTED_BACK_TO_ARRAY";
